### ISSUE TITLE
add recommendations for gh-pages

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/Scalatex#15]
I think some best-practises for managing gh-pages with scalatex would be useful in docs.

**Comment by mrmechko** [comment]
If it helps, here is the process I used to deploy `gh-pages` from `readme.scalatex`

#### Add the target files to git (`-f` to override `.gitignore`):

```git add -f readme/target/scalatex/```

#### Commit the files

#### Use `git subtree` to deploy the directory to `gh-pages`

```git subtree push --prefix readme/target/scalatex origin gh-pages```

**Comment by lihaoyi** [comment]
I've been doing something like

```bash
sbt readme/run
git checkout gh-pages
cp readme/target/scalatex/* .
git commit -am .
git push origin gh-pages:gh-pages
git checkout master
```

I bet it could be automated but I deploy infrequently enough that this has been enough for now

**Comment by caoilte** [comment]
I think 

https://github.com/sbt/sbt-ghpages

might be made to work. Advice on doing so in the docs would be great.

**Comment by olafurpg** [comment]
FWIW, I managed to get a nice setup with sbt-site and sbt-ghpages

```scala
// project/plugins.sbt
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-site" % "1.2.0")
// build.sbt
lazy val readme = scalatex
  .ScalatexReadme(projectId = "readme",
                  wd = file(""),
                  url = "https://github.com/org/repo/tree/master",
                  source = "Readme")
  .settings(
    allSettings,
    siteSourceDirectory := target.value / "scalatex",
    publish := {
      ghpagesPushSite
        .dependsOn(run.in(Compile).toTask(" --validate-links"))
        .value
    },
    git.remoteRepo := "git@github.com:org/repo.git" 
  )
  .enablePlugins(GhpagesPlugin)
```

`readme/publish` then takes care of generating the site and pushing it to gh-pages.

**Comment by olafurpg** [comment]
There is a section now in the docs explaining how to use scalatex with sbt-ghpages http://www.lihaoyi.com/Scalatex/#GitHubpages
