### ISSUE TITLE
Getting NoClassDefFound exception in run when using upickle as a dependency

### ISSUE THREAD

**Issue by mechkg** [lihaoyi/Scalatex#18]
I am trying to use a library (upickle) in a Scalatex project to generate some of the JSON examples that I need to include in the documentation.

My build.sbt looks like this:

    lazy val apiDocs = scalatex.ScalatexReadme(
      projectId = "ApiDocs",
      wd = file(""),
      url = "",
      source = "ApiDocs"
    ).settings(
      scalaVersion := "2.11.7",
      libraryDependencies += "com.lihaoyi" %% "upickle" % "0.3.4"
    ).dependsOn(sharedTypesJvm)

The ApiDocs.scalatex file does the following:
    `@import upickle.default._ `

Which compiles fine but when I try to generate a site using ApiDocs/run it crashes with the following:

    [error] (run-main-10) java.lang.NoClassDefFoundError: upickle/package$
    java.lang.NoClassDefFoundError: upickle/package$
        at scalatex.site.Sidebar$.snippet(Sidebar.scala:10)
        at scalatex.site.Main.bodyFrag(Main.scala:43)
        at scalatex.site.Main.bodyFrag(Main.scala:16)

<del>Apparently the upickle dependency does not end up on the classpath when `scalatex.ApiDocs().render` is run via the run task. How do I make sure that it does?</del> No, it's on the classpath (at least according to `show ApiDocs/runtime:fullClasspath`).

 It works as expected if I run that through `ApiDocs/console` rather than `ApiDocs/run`.

**Comment by mechkg** [comment]
I think I've found the cause for this error, it's actually enough to just have the upickle library on the dependency list for it to crash. 

The reason is that scalatex-site depends on upickle 0.2.7 and adding upickle 0.3.4 causes the older version to get evicted which breaks things.

Would it be difficult to update the dependency to a newer upickle version?

**Comment by lihaoyi** [comment]
Wouldn't be difficult to update, want to sent a diff to bring it up to
0.3.6?
