### ISSUE TITLE
Update scalatags to 0.6.0

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/Scalatex#29]
Hi,

we have a project which mixes some libs depending on the latest version of scalatags and on the latest version of scalatex. We get an error because of the API of scalatags 0.6.0 is binary incompatible with 0.5.x. Could you update the scalatags version of scalatex please?

Cheers,
Romain

**Comment by romainreuillon** [comment]
Hi @lihaoyi, any chance you will find the time to merge the PR and release a new version today?

**Comment by romainreuillon** [comment]
I tested this patch yesterday to generate our website and it works fine.

**Comment by lihaoyi** [comment]
Done in 0.3.6
