### ISSUE TITLE
Using @package lead to a blank page

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/Scalatex#6]
I wanted to use @package at the begining of a scalatex file.

P.scalatext:
```
@package p

content
```

Then I generated a site:
```
  val site = new scalatex.site.Site {
    def content =
      Map(
        "p.html" -> p.P()
      )
  }

  site.renderTo(args(0) + "/")
```

In this configuration it generates an empty html file.

Cheers,
Romain

**Comment by lihaoyi** [comment]
Cool. If anyone desperately needs custom packages, feel free to re-open or comment on this and maybe I can make it work somehow
