### ISSUE TITLE
Publish permission

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/Scalatex#64]
Hello @lihaoyi,

may you allow me to publish new version of scalatex on sonatype? My login is reuillon.

Cheers,
Romain

PS: thx for your interesting critical blog post on SBT, BTW ;)

**Comment by lihaoyi** [comment]
@olafurpg could you help @romainreuillon publish this? IIRC you used this project too at some point, and you already have the publishing keys :)

**Comment by olafurpg** [comment]
Sure thing :) @romainreuillon please contact me via olafurpg@gmail.com and I share with you the credentials.
