### ISSUE TITLE
How to make other dom elements

### ISSUE THREAD

**Issue by benjaminjackman** [lihaoyi/Scalatex#8]
So I am trying out scalatex to make a blog and I hit a stumbling point right away:
```
@html
  @head
    @title Ben's Blog
  @body
```
@title isn't defined this lead me to a couple questions:

1. What is the suggested way to include it?

2. **More importantly:** how can I just make any element I want? I tried this:
```scalatex
    @("title".tag){Ben's Blog}
```

but I got
```
[error] /home/bjackman/dev/github/blog/src/main/scalatex/biz/jackman/blog/Hello.scalatex:3: type mismatch;
[error]  found   : String("Ben\'s Blog")
[error]  required: scalatags.generic.Namespace
[error]     @("title".tag){Ben's Blog}
```

I didn't see anything in the documentation about how to use custom html tags

**Comment by lihaoyi** [comment]
Try

@("title".tag).apply{Ben's Blog}

or

@scalatags.Text.tags2.title{Ben's Blog}

Unfortunately, title conflicts between attributes and tags, and I figured
that more people use the attribute than the tag. There may be some clever
way to make it more seamless but for now that's the status quo

**Comment by benjaminjackman** [comment]
Hmm yep that is the issue,
Somewhat related, did you look at what japgolly did over in scala-js-react
to organize stuff a bit differently? Did you have any thoughts on that?

https://github.com/japgolly/scalajs-react/blob/master/doc/CHANGELOG-0.7.md#scalatags--vdom-major-changes

**Comment by benjaminjackman** [comment]
This is just a thought but if you used something like what he is proposing (< for elements and ^ for attributes) you could write it as

```
<html
  <head
    <title
  <body
    <a(^href := "#home")
```
Then save @ for just scala interpolation.

**Comment by lihaoyi** [comment]
You can already rename stuff however you want thanks to the magic of
imports, so if you want to rename things you can. You can even bundle
things into custom objects and save the import tax since they're all traits.

I rather like the way that @ is used for everything, so that's probably not
going to change =P HTML tags aren't special enough to break the rules

**Comment by lihaoyi** [comment]
FWIW you've been able to do all the things he describes (re-organize
imports, rename things, etc.) as far back as Scalatags 0.3.6; they're not
new features =P

**Comment by benjaminjackman** [comment]
Ok I've done the import trick before so I can do that for sure. I am really excited to be using this templating language, hopefully the intellij guys will notice this and adapt the play template file
magic to work on a scalatex files too, then this will be perfect! 

1. Right now how are you editing these files? I am just using intellij text file editing. Assigning the play2 filetype to handle .scalatex files gives some code complete, and also a lot of red.

2 . I know this is a bit silly to ask, from the docs "scalatags.Text.all._ is imported by default" is there any way to disable that import?

I just want to play around with the style a bit and see what it looks like, I think that while scalatags is really nice, scalatex could, in theory eventually transcend just html generation. To that end keeping the grammar simple and your design decision to "I rather like the way that @ is used for everything" is certainly the right one.

Thanks!

**Comment by lihaoyi** [comment]
> Right now how are you editing these files? I am just using intellij text file editing. Assigning the play2 filetype to handle .scalatex files gives some code complete, and also a lot of red.

I'm using intellij treating it as plaintext, or sublime as plaintext. Sublime does the indentation-wrapping much better.

> I know this is a bit silly to ask, from the docs "scalatags.Text.all._ is imported by default" is there any way to disable that import?

Right now, no. Furthermore, we're also hard-coding `[scalatags.Text.all.Frag]` as part of the generated code. If there's interest we can remove these hard-coded thingies, but for now it does what I want =P

**Comment by benjaminjackman** [comment]
Ok sounds good! I have a sublime license but I never really learned it so I
will use that as my quick and dirty scalatex editor.

Maybe someday scalac will run in scalajs and then there could be an ace
editor extension that compiles scalatex in html as you type right in the
web browser. Lacking that loop I think is what will limit scalatex from
overtaking stuff like markdown. Though I don't think it would be terribly
difficult to make a javascriptex variant.

BTW The tell intellij to treat the *.scalatex files as Play2 files has been
sort of working you might want to give it a shot.

Also have you considered having text on the same line as a tag be a child
of that tag?

e.g.

```scalatex
@ul
  @li Item 1
  @li Item 2
```

yielding

```scalatex
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
</ul>

```


This would make lists and other patterns like that shorter, I noticed when
reading the Readme.scalatex source most lines are just an single tag
followed by an indented line that has the contents of the tag. I am not
very experienced with indentation significant languages or the parse rules
of scalatex so I am not sure if this is a good idea or not.

**Comment by lihaoyi** [comment]
> Also have you considered having text on the same line as a tag be a child of that tag?

Yeah. I did that then backed it out. How would you make these two cases behave reasonable?

```scala
@li(id:="first") Hello
@li World

<li id="first">Hello</li>
<li>World</li>
```
```scala
@img(src:="www.scalatex.com/logo") Scalatex is a ...
<img src="www.scalatex.com/logo" /> Scalatex is a ...
```

I couldn't find a way. A sufficient number of my paragraphs of text start with a link, a bold, or some other tag that it was pwning everything all the time.

**Comment by benjaminjackman** [comment]
I understand now, normally you can just write tags like that inline and they won't swallow the following text, so when starting a line your brain has to flip to a different mode and say, this is the first tag in the line so it will consume the line, yeah I can see how that would trip things up.

As a workaround, I guess for the inline `li` example I can always use `@li{Item 1}` right? That's not really that bad.

**Comment by lihaoyi** [comment]
Yep that works ^_^
